config/routes.rb
ShopManagement::Application.routes.draw do
	
	resources :operators
	match 'login' => 'operator_sessions#new'
	match 'logout' => 'operator_sessions#destroy'
	resources :operator_sessions  

	match 'worksheets' => 'worksheets#worksheet'
	match 'worksheets/new_meeting' => 'worksheets#new_from_worksheet'
	match 'worksheets/create_meeting' => 'worksheets#create_into_worksheet'		
			

  match 'meetings/send_reminder/' => 'meetings#send_reminder'
	resources :meetings

	resources :customers

	resources :companies

	root :to => "welcome#index"
	get "welcome/index"

  match 'cron/send_alerts/' => 'cron#send_alerts'

  match 'admin' => 'administration#index'
  match 'admin/customers_upload' => 'administration#customers_upload'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base

  belongs_to :customer 	# foreign key: customer_id
	belongs_to :company 	# foreign key: company_id
	belongs_to :operator	# foreign key: operator_id

  validates_presence_of :start, :end
  validate  :start_date_cannot_be_in_the_past, \
            :end_date_cannot_be_in_the_past, \
            :start_should_precede_end

	def date
		self.start ? self.start.to_date : nil 
	end

  # Validation 

  def start_date_cannot_be_in_the_past
    errors.add(:start, I18n.translate('activerecord.errors.models.meeting.attributes.start.in_the_past')) if  
      !start.blank? and start < Date.today 
  end 

  def end_date_cannot_be_in_the_past
    errors.add(:end, I18n.translate('activerecord.errors.models.meeting.attributes.end.in_the_past')) if 
      !self.end.blank? and self.end < Date.today
  end 

  def start_should_precede_end
    errors.add(:start, I18n.translate('activerecord.errors.models.meeting.attributes.start.after_end')) if  
      !start.blank? and !self.end.blank? and self.end < start
  end

  # Business

  # Whether the alert for this meeting has been already delivered or not
  def alerted?
    !alert_sent.nil?
  end

end

app/controllers/meetings_controller.rb
require 'alert_job.rb'
class MeetingsController < ApplicationController

#  def send_reminder
#    @meeting = Meeting.find(params[:id])
#    mailMessage = AlertMailer.reminder(@meeting)
#    #mailMessage.delay.deliver
#    mailMessage.deliver
#    redirect_to(@meeting, :notice => t(:reminder_notice_correctly_sent))   
#  end

  def send_reminder_old
    @meeting = Meeting.find(params[:id])
    mailMessage = AlertMailer.reminder(@meeting)
#    mailMessage.delivery_method :smtp,   { :address   => "mail.xxxxxx",
#                                :port                 => 25,
#                                :domain               => 'localhost.localdomain',
#                                :user_name            => 'xxxx@xxxx.xxx',
#                                :password             => 'xxxxx',
#                                :authentication       => false,
#                                :enable_starttls_auto => true  }
    mailMessage.delivery_method :sendmail
#    mailMessage.delay.deliver
    mailMessage.deliver
    redirect_to(@meeting, :notice => t(:reminder_notice_correctly_sent))   
  end

  def send_reminder
    @meeting = Meeting.find(params[:id])
    alert_job = AlertJob.new
    alert_job.notifier_method = "reminder"
    alert_job.meeting_id = params[:id]
    Delayed::Job.enqueue alert_job
    redirect_to(@meeting, :notice => t(:reminder_notice_correctly_sent))   
  end

  def send_reminder_with_mail
    @meeting = Meeting.find(params[:id])
    mail = Mail.new do
        from @meeting.company.email_originator
        to @meeting.customer.email
        subject t(:reminder_mail_subject)
        body mail_body
    end
  end

  # GET /meetings
  # GET /meetings.xml
  def index

    @meetings = Meeting.joins(:company).where(Company.table_name => {:id => current_operator.company.id})

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.xml
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.xml
  def new
		@customers = Customer.joins(:company) \
      .where(Company.table_name => {:id => current_operator.company.id}) \
      .order("lastName ASC, firstName ASC")
		@operators = Operator.joins(:company).where(Company.table_name => {:id => current_operator.company.id})

		@meeting = Meeting.new
		if @start != nil then
			@meeting.start = @start if @start != nil
		end
		if @end != nil then
			@meeting.end = @end 
		end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
		@customers = Customer.all
		@operators = Operator.joins(:company).where(Company.table_name => {:id => current_operator.company.id})
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.xml
  def create
    @meeting = Meeting.new(params[:meeting])
		@meeting.company = current_operator.company

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to(@meeting, :notice => t(:meeting_notice_correctly_created) ) }
        format.xml  { render :xml => @meeting, :status => :created, :location => @meeting }
      else
    		@customers = Customer.joins(:company).where(Company.table_name => {:id => current_operator.company.id})
    		@operators = Operator.joins(:company).where(Company.table_name => {:id => current_operator.company.id})
        format.html { render :action => "new" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.xml
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to(@meeting, :notice => t(:meeting_notice_correctly_updated)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @meeting.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.xml
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to(meetings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |form| %>

  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('generic.error.form') %></h2>

      <ul>
        <% @meeting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :customer %><br />
    <% if @customers!=nil %>
      <%= form.select :customer_id, @customers.collect{|c| [c.firstName + " " + c.lastName, c.id]} %><br />
    <% else %>
      <!-- no customers -->
    <% end %>
  </div>

  <div class="field">
    <%= form.label :operator %>
    <br />
    <% if @operators!=nil %>
      <%= form.select \
        :operator_id, \
        @operators.collect{ |opr| [opr.first_name + " " + opr.last_name, opr.id]}, \
        {:include_blank => t("meeting.no_operator")} %>
    <% else %>
      <!-- no operators -->
    <% end %>
    <br />
  </div>

  <div class="field">
    <%= form.label :start %><br />
    <%= form.datetime_select :start %><br />
  </div>

  <div class="field">
    <%= form.label :end %><br />
    <%= form.datetime_select :end %><br />
  </div>

  <div class="field">
    <%= form.label :notes %><br />
    <%= form.text_area :notes %><br />
  </div>

  <div class="actions">
    <%= form.submit t("generic_button_ok") %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1><%=Meeting.human_name%></h1>
<%= link_to image_tag("icon_show.png", :border => 0), @meeting %>
<%= link_to image_tag("icon_back.png", :border => 0), meetings_path %>
<%= render 'form' %>

app/views/meetings/index.html.erb
<h1><%=Meeting.human_name(:count =>2)%></h1>
<%= link_to image_tag("icon_new.png", :border => 0), new_meeting_path %>

<table class="items">
  <thead>
    <tr>
      <th><%= Customer.human_name %></th>
      <th colspan="2"><%= Meeting.human_attribute_name(:start) %> - <%= Meeting.human_attribute_name(:end) %></th>
      <th><%= Operator.human_name %></th>
      <th><%= Meeting.human_attribute_name(:notes)%></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.customer.firstName %> <%= meeting.customer.lastName %></td>
        <td colspan="2">
          <%= l(meeting.start, :format => :date) %><br/>
          <%= l(meeting.start, :format => :time) %> - <%= l(meeting.end, :format => :time) %>
        </td>
        <td>
          <% if meeting.operator %>
            <%= meeting.operator.first_name %><%= meeting.operator.last_name %>
          <% else %>
            <%= t('meeting.no_operator') %>
          <% end %>
        </td>
        <td>
          <% unless meeting.notes.blank? %>
            <%= meeting.notes %>
          <% else %>
            <%= t('meeting.no_notes') %>
          <% end %>
        </td>
        <td class="controls">
          <div class="controls">
            <%= link_to image_tag("icon_show.png", :border => 0), meeting %>
            <%= link_to image_tag("icon_edit.png", :border => 0), edit_meeting_path(meeting) %>
            <%= link_to image_tag("icon_delete.png", :border => 0), meeting, :confirm => 'Are you sure?', :method => :delete %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meetings/new.html.erb
<h1><%=Meeting.human_name%></h1>
<%= link_to image_tag("icon_back.png", :border => 0), meetings_path %>
<%= render 'form' %>

app/views/meetings/show.html.erb
<%= link_to image_tag("icon_edit.png", :border => 0), edit_meeting_path(@meeting) %>
<%= link_to image_tag("icon_back.png", :border => 0), meetings_path %>
<!--
<%= link_to image_tag("icon_reminder.png", :border => 0), :controller => :meetings, :action => :send_reminder, :id => @meeting.id %>
-->

<p>
  <b><%=Customer.model_name.human%>:</b>
	<%= @meeting.customer.firstName %> <%= @meeting.customer.lastName %>
</p>

<p>
  <b><%=Operator.model_name.human%>:</b>
  <% if @meeting.operator %>
  	<%= @meeting.operator.first_name %> <%= @meeting.operator.last_name %>
  <% else %>
    <%= t('meeting.no_operator') %>
  <% end %>
</p>

<p>
  <b><%=Meeting.human_attribute_name(:start)%>:</b>
  <%= l(@meeting.start) %>
</p>

<p>
  <b><%=Meeting.human_attribute_name(:end)%>:</b>
  <%= l(@meeting.end) %>
</p>

<p>
  <b><%=Meeting.human_attribute_name(:notes)%>:</b>
  <% unless @meeting.notes.blank? %>
    <%= @meeting.notes %>
  <% else %>
    <%= t('meeting.no_notes') %>
  <% end %>
</p>