config/routes.rb
ShopManagement::Application.routes.draw do
	
	resources :operators
	match 'login' => 'operator_sessions#new'
	match 'logout' => 'operator_sessions#destroy'
	resources :operator_sessions  

	match 'worksheets' => 'worksheets#worksheet'
	match 'worksheets/new_meeting' => 'worksheets#new_from_worksheet'
	match 'worksheets/create_meeting' => 'worksheets#create_into_worksheet'		
			

  match 'meetings/send_reminder/' => 'meetings#send_reminder'
	resources :meetings

	resources :customers

	resources :companies

	root :to => "welcome#index"
	get "welcome/index"

  match 'cron/send_alerts/' => 'cron#send_alerts'

  match 'admin' => 'administration#index'
  match 'admin/customers_upload' => 'administration#customers_upload'

end

app/models/operator.rb
class Operator < ActiveRecord::Base

	acts_as_authentic # authlogic gem

  # Relation
  belongs_to :company # foreign key: company_id

  # Validation
  validates_presence_of :first_name, :last_name
end

app/controllers/operators_controller.rb
class Search

  def term
    @term
  end

  def parse(params)
    if params && params[:search] && params[:search][:term] && params[:search][:term].length > 0
      @term = params[:search][:term]
    end 
    return self
  end

  def active?
    return (@term != nil)
  end

end

class OperatorsController < ApplicationController

  def index    
    @search = Search.new.parse(params)

    if @search.active?
      @operators = Operator \
        .joins(:company) \
        .where(Company.table_name => {:id => current_operator.company.id}) \
        .where(["first_name LIKE ? OR last_name LIKE ?", "%" + @search.term + "%", "%" + @search.term + "%"]) \
        .paginate :page => params[:page], :order => 'last_name ASC', :per_page => 10
    else
      @operators = Operator.joins(:company).where(Company.table_name => {:id => current_operator.company.id}) \
      .paginate :page => params[:page], :order => 'last_name ASC', :per_page => 10
    end
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @customers }
    end
  end

  def new
		@operator = Operator.new
  end

  def create
		@operator = Operator.new(params[:operator])
    @operator.company = current_operator.company
    respond_to do |format|
		  if @operator.save
        format.html { 
          redirect_to(@operator, :notice => t('operator.notice.correctly_created'))
        }
        format.xml  { render :xml => @operator, :status => :created, :location => @operator }
		  else
        format.html { render :action => "new" }
        format.xml  { render :xml => @customer.errors, :status => :unprocessable_entity }
		  end			
    end
  end

  # GET /customers/1
  # GET /customers/1.xml
  def show
    @operator = Operator.find(params[:id])
    if(@operator.company == current_operator.company)
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @customer }
      end
    end
  end

	def edit
    @operator = Operator.find(params[:id])
	end

  
  def update
    @operator = Operator.find(params[:id])
    respond_to do |format|
      if @operator.update_attributes(params[:operator])
        format.html { 
          redirect_to(
            @operator, 
            :notice => t('operator.notice.correctly_updated') 
          ) 
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @operator.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @operator = Operator.find(params[:id])
    if @current_operator != @operator
      @operator.destroy
      flash[:notice]= t('operator.notice.correctly_removed')
    else
      flash[:error]= t('operator.error.cannot_remove_self')
    end

    respond_to do |format|
      format.html { redirect_to(operators_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/operator_helper.rb
module OperatorHelper
end

app/views/operators/_form.html.erb
<%= form_for(@operator) do |form| %>

  <% if @operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('generic.error.form') %></h2>

      <ul>
      <% @operator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= form.label :first_name %><br />
		<%= form.text_field :first_name %><br />
	</div>

	<div class="field">
		<%= form.label :last_name %><br />
		<%= form.text_field :last_name %><br />
	</div>

	<div class="field">
		<%= form.label :username %><br />
    <% if @operator.username && @operator.username.length > 0 %>
      <%= @operator.username %>
    <% else %>
		  <%= form.text_field :username %>
    <% end %>
    <br />
	</div>

	<div class="field">
		<%= form.label :password %><br />
		<%= form.password_field :password %><br />
	</div>

	<div class="field">
		<%= form.label :password_confirmation %><br />
		<%= form.password_field :password_confirmation %><br />
	</div>

	<div class="actions">
		<%= form.submit %>
	</div>
<% end %>

app/views/operators/edit.html.erb
<h1><%=Operator.model_name.human%></h1>
<%= link_to image_tag("icon_show.png", :border => 0), @operator %>
<%= link_to image_tag("icon_back.png", :border => 0), operators_path %>

<%= render 'form' %>

app/views/operators/index.html.erb
<h1><%=Operator.human_name(:count =>2)%></h1>
<%= link_to image_tag("icon_new.png", :border => 0), new_operator_path %>

<%= form_for :search, :url => operators_path, :html => {:method => :get} do |f| %>
  <%= f.search_field :term %>
  <%= image_submit_tag 'icon_search.png' %>
<% end %>


<table class="items">
  <thead>
	<tr>
		<th><%= Operator.human_attribute_name(:first_name) %></th>
		<th><%= Operator.human_attribute_name(:last_name) %></th>
		<th><%= Operator.human_attribute_name(:username) %></th>
		<th colspan="1"></th>
	</tr>
  </thead>
  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td><%= operator.first_name %></td>
        <td><%= operator.last_name %></td>
        <td><%= operator.username %></td>
        <td class="controls">
          <div class="controls">
            <%= link_to image_tag("icon_show.png", :border => 0), operator %>
            <%= link_to image_tag("icon_edit.png", :border => 0), edit_operator_path(operator) %>
            <% if @current_operator != operator %>
              <%= link_to \
                image_tag("icon_delete.png", :border => 0), \
                operator, \
                :confirm => t('generic.button.delete.confirmation'), \
                :method => :delete %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @operators %>

app/views/operators/new.html.erb
<h1><%=Operator.model_name.human%></h1>
<%= render 'form' %>

app/views/operators/show.html.erb
<%= link_to image_tag("icon_edit.png", :border => 0), edit_operator_path(@operator) %>
<%= link_to image_tag("icon_back.png", :border => 0), operators_path %>

<p>
  <b><%= Operator.human_attribute_name(:first_name) %>:</b>
  <%= @operator.first_name %>
</p>

<p>
  <b><%= Operator.human_attribute_name(:last_name) %>:</b>
  <%= @operator.last_name %>
</p>

<p>
  <b><%= Operator.human_attribute_name(:username) %></b>
  <%= @operator.username %>
</p>