config/routes.rb
ShopManagement::Application.routes.draw do
	
	resources :operators
	match 'login' => 'operator_sessions#new'
	match 'logout' => 'operator_sessions#destroy'
	resources :operator_sessions  

	match 'worksheets' => 'worksheets#worksheet'
	match 'worksheets/new_meeting' => 'worksheets#new_from_worksheet'
	match 'worksheets/create_meeting' => 'worksheets#create_into_worksheet'		
			

  match 'meetings/send_reminder/' => 'meetings#send_reminder'
	resources :meetings

	resources :customers

	resources :companies

	root :to => "welcome#index"
	get "welcome/index"

  match 'cron/send_alerts/' => 'cron#send_alerts'

  match 'admin' => 'administration#index'
  match 'admin/customers_upload' => 'administration#customers_upload'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <%= csrf_meta_tag %>

    <title><%=t :application_title %> - <%=t(:application_credits) %></title>
    <link rel="icon" href="/favico.png" type="image/ico" />
    <link rel="shortcut icon" href="/favico.png" type="image/ico" />
    <%= stylesheet_link_tag :all %>
    <%= stylesheet_link_tag ['smoothness/jquery-ui-1.8.7.custom'] %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag ['jquery-1.4.4.min'] %>
    <%= javascript_include_tag ['jquery-ui-1.8.7.custom.min'] %>
    <%= javascript_include_tag ['application-jquery'] %>
    <%= yield :head %>

  </head>

  <body>

    <div id="header">
      <%= link_to t(:application_title), "/welcome/index" %>
      <br/>
      <small><%=t :application_tagline %></small>
    </div>



    <div id="operator_nav">
      <% if current_operator %>
        <%= current_operator.first_name %>
        <%= current_operator.last_name %>,
        <%= current_operator.company.name %>
        |
        <%= link_to t("login_profile"), edit_operator_path(current_operator) %>
        |
        <%= link_to t("login_log_out"), logout_path %>
      <% else %>
        <%= form_for OperatorSession.new do |form| %>
          <%= t 'login.username' %>
          <%= form.text_field :username, :size => 10 %>
          <%= t 'login.password' %>
          <%= form.password_field :password, :size =>10 %>
          <%= form.submit t("login_log_in") %>
        <% end %>
      <% end %>
    </div>

    <% if flash && flash.count > 0 %>
      <div class="flash">
        <% if flash[:error] %>
          <div class="flash_error"><%= flash[:error] %></div>
        <% end %>
        <% if flash[:warning] %>
          <div class="flash_warning"><%= flash[:warning] %></div>
        <% end %>
        <% if flash[:notice] %>
          <div class="flash_notice"><%= flash[:notice] %></div>
        <% end %>
      <% end %>
    </div>


    <% if current_operator %>
      <div id="menu_container">
        <ul id="menu_list">
          <% if current_operator.role == :application_admin.to_s %>
            <li><%= link_to Company.model_name.human(:count =>2), companies_path %></li>
          <% end %>
          <li><%= link_to Operator.model_name.human(:count =>2), operators_path %></li>
          <li><%= link_to Customer.model_name.human(:count =>2), customers_path %></li>
          <li><%= link_to Meeting.model_name.human(:count =>2), meetings_path %></li>
          <li><%= link_to t("worksheet.title"), "/worksheets" %></li>
          <li><%= link_to t("administration.title"), "/admin" %></li>
        </ul>
      </div>
    <% end %>

    <div id="content">
      <%= yield %>
    </div>

  </body>
</html>